### ISSUE TITLE
change process name to `sorted`

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-ephys-results-collector#1]
Process name is a token used in the "name" of the result asset, which is leading to names that look like this:

`ecephys_615047_2022-07-13_14-15-51_Spike Sorting_2023-07-20_10-08-36`

https://github.com/AllenNeuralDynamics/aind-capsule-ephys-results-collector/blob/859e9581dfdef5567b402c3ff5b3aad02b562b8b/code/run_capsule.py#L143

Please change this to `sorted`.

**Comment by alejoe91** [comment]
And here for the capsule: https://github.com/AllenNeuralDynamics/aind-capsule-ephys-spikesort-kilosort25-full/pull/9
